project_id = "imnmjgyjdkigppphwdbq"

[functions.admin-users]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.subscribe-digest]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = false
